version: '3'

services:
  # Postgres
  db:
    image: postgres:9.6.4
    environment:
      - POSTGRES_PASSWORD=!!Docker##is^^nice9
    volumes:
      - ./database/postgresql:/var/lib/postgresql/data
  
  # Redis
  redis:
    image: redis:4.0.1

  # Django Web Server
  web:
    build: .
    command: ./run_web.sh
    volumes:
      - .:/code
    ports:
      - "80:8000"
    links:
      - db
      - redis
    depends_on:
      - db

  # Celery Worker
  worker:
    build: .
    command: > 
              bash -c "sleep 12 && celery worker 
              --app mhtportal 
              --loglevel INFO 
              --logfile ./logs/worker.log"
    volumes:
      - .:/code
    links:
      - db
      - redis
    depends_on:
      - redis

  # Celery Beat
  beat:
    build: .
    command: > 
              bash -c "sleep 15 && celery beat 
              --app mhtportal 
              --loglevel INFO 
              --logfile ./logs/beat.log"
    volumes:
      - .:/code
    links:
      - db
      - redis
    depends_on:
      - redis
